version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: packing-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/quasar-project
    container_name: packing-frontend
    ports:
      - "9000:9000"
    working_dir: /app
    restart: unless-stopped